## SITE A
title: Site A
publishDir: public/site_a

module:
  imports:
    # Content
    # -> Hugolify content types and taxonomies available https://www.hugolify.io/docs/sections/
    - path: github.com/hugolify/hugolify-theme-posts

    # Core theme
    - path: github.com/hugolify/hugolify-theme

    # Admin
    - path: github.com/hugolify/hugolify-admin

  # Get specifi contents
  mounts:
    # Index posts file
    - source: 'content/site_a/posts.md'
      target: 'content/posts/_index.md'

    # Posts
    - source: 'content/posts'
      target: 'content/posts'

    # Sitemap
    - source: 'content/sitemap'
      target: 'content/sitemap'

    # Content
    - source: 'content/site_a'
      target: 'content'

    # Menu
    - source: 'data/menu/site_a'
      target: 'data/menu'

    # SASS Variables
    - source: 'assets/sass/abstracts/_variables-site-a.sass'
      target: 'assets/sass/abstracts/_variables-site.sass'

# Set site param
params:
  _merge: deep
  site: site_a
  logo:
    header: '/assets/images/logo_site-a.svg'
    footer: '/assets/images/logo_site-a.svg'
  share: '/assets/images/share_site-a.png'

  # Admin
  admin:
    # Disable nested pages
    nested:
      depth: 1

    collections:
      # Disable originals collections
      indexes:
        enable: false
      pages:
        enable: false

      # Enable all sites
      site_a:
        enable: true
      site_b:
        enable: true
