## SITE A
title: Site B
publishDir: public/site_b

module:
  imports:
    # Content
    # -> Hugolify content types and taxonomies available https://www.hugolify.io/docs/sections/
    - path: github.com/hugolify/hugolify-theme-posts

    # Core theme
    - path: github.com/hugolify/hugolify-theme

  # Get specifi contents
  mounts:
    # Index posts file
    - source: 'content/site_b/posts.md'
      target: 'content/posts/_index.md'

    # Posts
    - source: 'content/posts'
      target: 'content/posts'

    # Sitemap
    - source: 'content/sitemap'
      target: 'content/sitemap'

    # Content
    - source: 'content/site_b'
      target: 'content'

    # Data
    - source: 'data/site_b'
      target: 'data'

    # SASS Variables
    - source: 'assets/sass/abstracts/_variables-site-b.sass'
      target: 'assets/sass/abstracts/_variables-site.sass'

# Set site param
params:
  _merge: deep
  site: site_b
  logo:
    header: '/assets/images/logo_site-b.svg'
    footer: '/assets/images/logo_site-b.svg'
  share: '/assets/images/share_site-b.png'
